ALTER TABLE "leads" ADD COLUMN "applicant_role" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "is_currently_studying" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "current_year_or_graduated" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "current_status" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "bachelor_school" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "bachelor_gpa" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "bachelor_program_name" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "graduated_bachelor_school" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "graduated_bachelor_program" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "graduated_bachelor_gpa" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "master_school" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "master_program_name" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "master_gpa" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "highest_education" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "highschool_name" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "highschool_gpa" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "intended_programs" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "intended_direction" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "intended_start_time" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "program_level" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "english_level" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "german_level" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "work_experience" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "other_activities" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "awards" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "additional_info" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "reason_for_germany" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "reasons_to_study_abroad" text;--> statement-breakpoint
ALTER TABLE "leads" ADD COLUMN "promo_code" text;