import {
  pgTable,
  text,
  timestamp,
  integer,
  jsonb,
  boolean
} from 'drizzle-orm/pg-core';
import { nanoid } from 'nanoid';

export const aiAssistConversations = pgTable('ai_assist_conversations', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => nanoid()),
  ownerUserId: text('owner_user_id').notNull(),
  ownerRole: text('owner_role').notNull(),
  studentId: text('student_id'),
  studentDisplayName: text('student_display_name'),
  // True when the conversation was started as a structured student deep-dive
  // (Student Analysis view). Lets the portfolio reload the last persisted
  // analysis for a student instead of re-running it on every cold load.
  analysisMode: boolean('analysis_mode').notNull().default(false),
  title: text('title').notNull().default('New AI Assist conversation'),
  titleAutoGenerated: boolean('title_auto_generated').notNull().default(true),
  titleUpdatedByUser: boolean('title_updated_by_user').notNull().default(false),
  titleGeneratedAt: timestamp('title_generated_at'),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow()
});

export const aiAssistMessages = pgTable('ai_assist_messages', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => nanoid()),
  conversationId: text('conversation_id')
    .notNull()
    .references(() => aiAssistConversations.id, { onDelete: 'cascade' }),
  role: text('role').notNull(),
  content: text('content').notNull(),
  model: text('model'),
  responseId: text('response_id'),
  usage: jsonb('usage'),
  skillTrace: jsonb('skill_trace'),
  linkHints: jsonb('link_hints'),
  createdAt: timestamp('created_at').defaultNow()
});

export const aiAssistToolCalls = pgTable('ai_assist_tool_calls', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => nanoid()),
  conversationId: text('conversation_id')
    .notNull()
    .references(() => aiAssistConversations.id, { onDelete: 'cascade' }),
  assistantMessageId: text('assistant_message_id').references(
    () => aiAssistMessages.id,
    { onDelete: 'cascade' }
  ),
  toolName: text('tool_name').notNull(),
  arguments: jsonb('arguments'),
  result: jsonb('result'),
  status: text('status').notNull(),
  durationMs: integer('duration_ms'),
  permissionOutcome: jsonb('permission_outcome'),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at').defaultNow()
});

export type AiAssistConversation = typeof aiAssistConversations.$inferSelect;
export type NewAiAssistConversation = typeof aiAssistConversations.$inferInsert;
export type AiAssistMessage = typeof aiAssistMessages.$inferSelect;
export type NewAiAssistMessage = typeof aiAssistMessages.$inferInsert;
export type AiAssistToolCall = typeof aiAssistToolCalls.$inferSelect;
export type NewAiAssistToolCall = typeof aiAssistToolCalls.$inferInsert;
