name: Run Tests

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to client directory
        run: cd client

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run-script test